# Generated by Django 3.1.6 on 2021-03-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20210310_1440'),
        ('clinic', '0031_auto_20210311_1126'),
        ('finance', '0002_auto_20210119_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadonchuoikham',
            name='chuoi_kham',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don_dich_vu', to='clinic.chuoikham'),
        ),
        migrations.AlterField(
            model_name='hoadonlamsang',
            name='lich_hen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don_lam_sang', to='clinic.lichhenkham'),
        ),
        migrations.AlterField(
            model_name='hoadonthuoc',
            name='don_thuoc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don_thuoc', to='medicine.donthuoc'),
        ),
    ]
