# Generated by Django 3.1.7 on 2021-03-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210317_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoadonchuoikham',
            options={'permissions': (('can_checkout_service_receipt', 'Thanh toán hóa đơn dịch vụ kỹ thuật'), ('can_view_service_receipt', 'Xem hóa đơn dịch vụ kỹ thuật'), ('can_delete_service_receipt', 'Xóa hóa đơn dịch vụ kỹ thuật'), ('can_print_service_receipt', 'In hóa đơn dịch vụ kỹ thuật'), ('can_view_service_expense_coverage', 'Xem danh sách dịch vụ kỹ thuật bảo hiểm chi trả'), ('can_export_service_expense_coverage', 'Xuất danh sách dịch vụ kỹ thuật bảo hiểm chi trả'), ('can_view_service_revenue', 'Xem doanh thu dịch vụ kỹ thuật')), 'verbose_name': 'Hóa Đơn Chuỗi Khám', 'verbose_name_plural': ('Hóa Đơn Chuỗi Khám',)},
        ),
        migrations.AlterModelOptions(
            name='hoadonlamsang',
            options={'permissions': (('can_checkout_clinical_receipt', 'Thanh toán hóa đơn lâm sàng'), ('can_view_clinical_receipt', 'Xem hóa đơn lâm sàng'), ('can_delete_clinical_receipt', 'Xóa hóa đơn lâm sàng'), ('can_view_clinical_revenue', 'Xem doanh thu lâm sàng')), 'verbose_name': 'Hóa Đơn Lâm Sàng', 'verbose_name_plural': ('Hóa Đơn Lâm Sàng',)},
        ),
        migrations.AlterModelOptions(
            name='hoadonthuoc',
            options={'permissions': (('can_checkout_medicine_receipt', 'Thanh toán hóa đơn thuốc'), ('can_view_medicine_receipt', 'Xem hóa đơn thuốc'), ('can_delete_medicine_receipt', 'Xóa hóa đơn thuốc'), ('can_print_medicine_receipt', 'In hóa đơn thuốc'), ('can_view_medicine_expense_coverage', 'Xem danh sách thuốc bảo hiểm chi trả'), ('can_export_medicine_expense_coverage', 'Xuất danh sách thuốc bảo hiểm chi trả'), ('can_view_medicine_revenue', 'Xem doanh thu thuốc')), 'verbose_name': 'Hóa Đơn Thuốc', 'verbose_name_plural': ('Hóa Đơn Thuốc',)},
        ),
        migrations.AlterModelOptions(
            name='hoadonvattu',
            options={'permissions': (('can_checkout_medical_supplies_receipt', 'Thanh toán hóa đơn vật tư y tế'), ('can_view_medical_supplies_receipt', 'Xem hóa đơn vật tư y tế'), ('can_delete_medical_supplies_receipt', 'Xóa hóa đơn vật tư y tế'), ('can_print_medical_supplies_receipt', 'In hóa đơn vật tư y tế'), ('can_view_medical_supplies_expense_coverage', 'Xem danh sách vật tư y tế bảo hiểm chi trả'), ('can_export_medical_supplies_expense_coverage', 'Xuất danh sách vật tư y tế bảo hiểm chi trả'), ('can_view_medical_supplies_revenue', 'Xem doanh thu vật tư y tế')), 'verbose_name': 'Hóa Đơn Vật Tư Y Tế', 'verbose_name_plural': ('Hóa Đơn Vật Tư Y Tế',)},
        ),
    ]
