# Generated by Django 3.2 on 2021-06-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20210511_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadonchuoikham',
            name='thoi_gian_tao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoadonlamsang',
            name='thoi_gian_cap_nhat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoadonlamsang',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoadonthuoc',
            name='thoi_gian_cap_nhat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoadonthuoc',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
