# Generated by Django 3.1.5 on 2021-01-19 16:23

import clinic.models
from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ma_benh_nhan', models.CharField(max_length=20, null=True, unique=True)),
                ('so_dien_thoai', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='(84|0[3|5|7|8|9])+([0-9]{8})\\b')])),
                ('ho_ten', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('cmnd_cccd', models.CharField(max_length=13, null=True, unique=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nu')], max_length=10, null=True)),
                ('anh_dai_dien', models.FileField(blank=True, max_length=1000, null=True, upload_to=clinic.models.file_url)),
                ('dia_chi', models.TextField(blank=True, max_length=1000, null=True)),
                ('dan_toc', models.CharField(blank=True, max_length=40, null=True)),
                ('chuc_nang', models.CharField(choices=[('1', 'Người Dùng'), ('2', 'Lễ Tân'), ('3', 'Bác Sĩ Lâm Sàng'), ('4', 'Bác Sĩ Chuyên Khoa'), ('5', 'Nhân Viên Phòng Tài Chính'), ('6', 'Nhân Viên Phòng Thuốc'), ('7', 'Quản Trị Viên')], default='1', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('ma_so_bao_hiem', models.CharField(blank=True, max_length=25, null=True)),
                ('muc_bao_hiem', models.PositiveIntegerField(blank=True, null=True)),
                ('so_diem_tich', models.PositiveIntegerField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChiSoXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_chi_so', models.CharField(blank=True, max_length=10, null=True)),
                ('ten_chi_so', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Chỉ Số Xét Nghiệm',
                'verbose_name_plural': 'Chỉ Số Xét Nghiệm',
            },
        ),
        migrations.CreateModel(
            name='ChiTietChiSoXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_so_binh_thuong_min', models.CharField(blank=True, max_length=10, null=True)),
                ('chi_so_binh_thuong_max', models.CharField(blank=True, max_length=10, null=True)),
                ('chi_so_binh_thuong', models.CharField(blank=True, max_length=10, null=True)),
                ('don_vi_do', models.CharField(blank=True, max_length=50, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Chi Tiết Chỉ Số Xét Nghiệm',
                'verbose_name_plural': 'Chi Tiết Chỉ Số Xét Nghiệm',
            },
        ),
        migrations.CreateModel(
            name='ChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tai_kham', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
                ('bac_si_dam_nhan', models.ForeignKey(blank=True, null=True, on_delete=models.SET(clinic.models.get_sentinel_user), related_name='bac_si_chuoi_kham', to=settings.AUTH_USER_MODEL)),
                ('benh_nhan', models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_user), related_name='chuoi_kham', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chuỗi Khám',
                'verbose_name_plural': 'Chuỗi Khám',
            },
        ),
        migrations.CreateModel(
            name='DichVuKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dvkt', models.CharField(blank=True, max_length=50, null=True)),
                ('stt', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('ten_dvkt', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_gia', models.CharField(blank=True, max_length=50, null=True)),
                ('don_gia', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('quyet_dinh', models.CharField(blank=True, max_length=10, null=True)),
                ('cong_bo', models.CharField(blank=True, max_length=10, null=True)),
                ('ma_cosokcb', models.CharField(blank=True, max_length=20, null=True)),
                ('ten_dich_vu', models.CharField(blank=True, max_length=255, null=True)),
                ('bao_hiem', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dịch Vụ Khám',
                'verbose_name_plural': 'Dịch Vụ Khám',
            },
        ),
        migrations.CreateModel(
            name='DoTuoiXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_tuoi_min', models.PositiveIntegerField(blank=True, null=True)),
                ('do_tuoi_max', models.PositiveIntegerField(blank=True, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Độ Tuổi Xét Nghiệm',
                'verbose_name_plural': 'Độ Tuổi Xét Nghiệm',
            },
        ),
        migrations.CreateModel(
            name='FileKetQua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=clinic.models.file_url)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tài Liệu',
                'verbose_name_plural': 'Tài Liệu',
            },
        ),
        migrations.CreateModel(
            name='KetQuaChuyenKhoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ket_qua', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
                ('ket_luan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kết Quả Chuyên Khoa',
                'verbose_name_plural': 'Kết Quả Chuyên Khoa',
            },
        ),
        migrations.CreateModel(
            name='LichHenKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField()),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('ly_do', models.TextField(blank=True, null=True)),
                ('dia_diem', models.CharField(blank=True, max_length=255, null=True)),
                ('loai_dich_vu', models.CharField(blank=True, choices=[('kham_chua_benh', 'Khám Chữa Bệnh'), ('kham_suc_khoe', 'Khám Sức Khỏe')], max_length=25, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(auto_now=True, null=True)),
                ('benh_nhan', models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_user), related_name='benh_nhan_hen_kham', to=settings.AUTH_USER_MODEL)),
                ('nguoi_phu_trach', models.ForeignKey(blank=True, null=True, on_delete=models.SET(clinic.models.get_sentinel_user), related_name='nguoi_phu_trach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch Hẹn Khám',
                'verbose_name_plural': 'Lịch Hẹn Khám',
            },
        ),
        migrations.CreateModel(
            name='PhongChucNang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_chuc_nang', models.CharField(max_length=255)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
                ('bac_si_phu_trach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bac_si_chuyen_khoa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phòng Chức Năng',
                'verbose_name_plural': 'Phòng Chức Năng',
            },
        ),
        migrations.CreateModel(
            name='TinhTrangPhongKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kha_dung', models.BooleanField(default=True)),
                ('thoi_gian_dong_cua', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_mo_cua', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longtitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrangThaiChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_chuoi_kham', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Trạng Thái Chuỗi Khám',
                'verbose_name_plural': 'Trạng Thái Chuỗi Khám',
            },
        ),
        migrations.CreateModel(
            name='TrangThaiKhoaKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_khoa_kham', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Trạng Thái Khoa Khám',
                'verbose_name_plural': 'Trạng Thái Khoa Khám',
            },
        ),
        migrations.CreateModel(
            name='TrangThaiLichHen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_trang_thai', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Trạng Thái Lịch Hẹn',
                'verbose_name_plural': 'Trạng Thái Lịch Hẹn',
            },
        ),
        migrations.CreateModel(
            name='ProfilePhongChucNang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_cho', models.PositiveIntegerField(blank=True, null=True)),
                ('thoi_gian_trung_binh', models.PositiveIntegerField(blank=True, help_text='Đơn vị(phút)', null=True)),
                ('status', models.BooleanField(default=True)),
                ('phong_chuc_nang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_phong_chuc_nang', to='clinic.phongchucnang')),
            ],
        ),
        migrations.CreateModel(
            name='PhongKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_kham', models.CharField(max_length=255)),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('so_dien_thoai', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to=clinic.models.file_url)),
                ('gia_tri_diem_tich', models.PositiveIntegerField(blank=True, null=True)),
                ('chu_khoan', models.CharField(blank=True, max_length=255, null=True)),
                ('so_tai_khoan', models.CharField(blank=True, max_length=20, null=True)),
                ('thong_tin_ngan_hang', models.TextField(blank=True, null=True)),
                ('tinh_trang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.tinhtrangphongkham')),
            ],
            options={
                'verbose_name': 'Phòng Khám',
                'verbose_name_plural': 'Phòng Khám',
            },
        ),
        migrations.CreateModel(
            name='PhanKhoaKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bao_hiem', models.BooleanField(default=False)),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('thoi_gian_bat_dau', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
                ('bac_si_lam_sang', models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_user), related_name='bac_si', to=settings.AUTH_USER_MODEL)),
                ('benh_nhan', models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('chuoi_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phan_khoa_kham', to='clinic.chuoikham')),
                ('dich_vu_kham', models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_dich_vu), related_name='phan_khoa_dich_vu', to='clinic.dichvukham')),
                ('trang_thai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.trangthaikhoakham')),
            ],
            options={
                'verbose_name': 'Phân Khoa Khám',
                'verbose_name_plural': 'Phân Khoa Khám',
            },
        ),
        migrations.CreateModel(
            name='LichSuTrangThaiLichHen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.CharField(blank=True, max_length=500, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('lich_hen_kham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen', to='clinic.lichhenkham')),
                ('trang_thai_lich_hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trang_thai_lich_hen', to='clinic.trangthailichhen')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuTrangThaiKhoaKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.CharField(blank=True, max_length=500, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('phan_khoa_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.phankhoakham')),
                ('trang_thai_khoa_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.trangthaikhoakham')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.CharField(blank=True, max_length=500, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('chuoi_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.chuoikham')),
                ('trang_thai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.trangthaichuoikham')),
            ],
        ),
        migrations.AddField(
            model_name='lichhenkham',
            name='trang_thai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.trangthailichhen'),
        ),
        migrations.CreateModel(
            name='KetQuaXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ket_qua_xet_nghiem', models.CharField(blank=True, max_length=50, null=True)),
                ('danh_gia_chi_so', models.CharField(blank=True, choices=[('1', 'Bình thường'), ('0', 'Bất bình thường')], max_length=5, null=True)),
                ('danh_gia_ghi_chu', models.CharField(blank=True, max_length=100, null=True)),
                ('chi_so_xet_nghiem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.chisoxetnghiem')),
                ('ket_qua_chuyen_khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.ketquachuyenkhoa')),
                ('phan_khoa_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.phankhoakham')),
            ],
            options={
                'verbose_name': 'Kết Quả Xét Nghiệm',
                'verbose_name_plural': 'Kết Quả Xét Nghiệm',
            },
        ),
        migrations.CreateModel(
            name='KetQuaTongQuat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ket_qua', models.CharField(blank=True, max_length=50, null=True)),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
                ('ket_luan', models.TextField(blank=True, null=True)),
                ('chuoi_kham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ket_qua_tong_quat', to='clinic.chuoikham')),
            ],
            options={
                'verbose_name': 'Kết Quả Tổng Quát',
                'verbose_name_plural': 'Kết Quả Tổng Quát',
            },
        ),
        migrations.AddField(
            model_name='ketquachuyenkhoa',
            name='ket_qua_tong_quat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua_chuyen_khoa', to='clinic.ketquatongquat'),
        ),
        migrations.CreateModel(
            name='GiaDichVu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.DecimalField(decimal_places=3, max_digits=10)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(blank=True, null=True)),
                ('id_dich_vu_kham', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gia_dich_vu_kham', to='clinic.dichvukham')),
            ],
        ),
        migrations.CreateModel(
            name='FileKetQuaTongQuat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tong_quat', to='clinic.fileketqua')),
                ('ket_qua_tong_quat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_ket_qua_tong_quat', to='clinic.ketquatongquat')),
            ],
            options={
                'verbose_name': 'File Kết Quả Tổng Quát',
                'verbose_name_plural': 'File Kết Quả Tổng Quát',
            },
        ),
        migrations.CreateModel(
            name='FileKetQuaChuyenKhoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_chuyen_khoa', to='clinic.fileketqua')),
                ('ket_qua_chuyen_khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_ket_qua_chuyen_khoa', to='clinic.ketquachuyenkhoa')),
            ],
            options={
                'verbose_name': 'File Kết Quả Chuyên Khoa',
                'verbose_name_plural': 'File Kết Quả Chuyên Khoa',
            },
        ),
        migrations.CreateModel(
            name='DoiTuongXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gioi_tinh', models.CharField(blank=True, choices=[('1', 'Nam'), ('2', 'Nữ'), ('3', 'Chưa Xác Định')], max_length=5, null=True)),
                ('do_tuoi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.dotuoixetnghiem')),
            ],
            options={
                'verbose_name': 'Đối Tượng Xét Nghiệm',
                'verbose_name_plural': 'Đối Tượng Xét Nghiệm',
            },
        ),
        migrations.AddField(
            model_name='dichvukham',
            name='phong_chuc_nang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dich_vu_kham_theo_phong', to='clinic.phongchucnang'),
        ),
        migrations.AddField(
            model_name='chuoikham',
            name='lich_hen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_sach_chuoi_kham', to='clinic.lichhenkham'),
        ),
        migrations.AddField(
            model_name='chuoikham',
            name='trang_thai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trang_thai', to='clinic.trangthaichuoikham'),
        ),
        migrations.AddField(
            model_name='chisoxetnghiem',
            name='chi_tiet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.chitietchisoxetnghiem'),
        ),
        migrations.AddField(
            model_name='chisoxetnghiem',
            name='dich_vu_kham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.dichvukham'),
        ),
        migrations.AddField(
            model_name='chisoxetnghiem',
            name='doi_tuong_xet_nghiem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doituongxetnghiem'),
        ),
        migrations.CreateModel(
            name='BaoHiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_bao_hiem', models.CharField(max_length=255)),
                ('dang_bao_hiem', models.SmallIntegerField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField()),
                ('thoi_gian_chinh_sua', models.DateTimeField()),
                ('id_dich_vu_kham', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bao_hiem_dich_vu_kham', to='clinic.dichvukham')),
            ],
        ),
        migrations.CreateModel(
            name='BaiDang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.TextField(blank=True, null=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to=clinic.models.file_url)),
                ('noi_dung_chinh', models.TextField(blank=True, null=True)),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('thoi_gian_bat_dau', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('nguoi_dang_bai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_dang_bai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài Đăng',
                'verbose_name_plural': 'Bài Đăng',
            },
        ),
        migrations.CreateModel(
            name='BacSi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gioi_thieu', models.TextField(blank=True, null=True)),
                ('chuc_danh', models.CharField(blank=True, max_length=255, null=True)),
                ('chuyen_khoa', models.CharField(blank=True, max_length=255, null=True)),
                ('noi_cong_tac', models.TextField(blank=True, null=True)),
                ('kinh_nghiem', models.TextField(blank=True, null=True)),
                ('loai_cong_viec', models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time')], max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bác Sĩ',
                'verbose_name_plural': 'Bác Sĩ',
            },
        ),
    ]
