# Generated by Django 3.1.5 on 2021-01-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichvukham',
            name='chi_so',
            field=models.BooleanField(default=False),
        ),
    ]
