# Generated by Django 3.1.5 on 2021-01-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20210120_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucBenh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_benh', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_benh', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DanhMucKhoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(blank=True, null=True)),
                ('ma_khoa', models.CharField(blank=True, max_length=5, null=True)),
                ('ten_khoa', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuongDungThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(blank=True, null=True)),
                ('ma_duong_dung', models.CharField(blank=True, max_length=5, null=True)),
                ('ten_duong_dung', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoiThau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_goi', models.CharField(blank=True, max_length=5, null=True)),
                ('goi', models.CharField(blank=True, max_length=255, null=True)),
                ('nhom', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_nhom', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhomChiPhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom', models.CharField(blank=True, max_length=2, null=True)),
                ('ten_nhom', models.CharField(blank=True, max_length=255, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhomTaiNan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom', models.CharField(blank=True, max_length=2, null=True)),
                ('ten_nhom', models.CharField(blank=True, max_length=100, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_may', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_may', models.CharField(blank=True, max_length=255, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bacsi',
            name='chung_chi_hanh_nghe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chuoikham',
            name='ma_lk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dichvukham',
            name='tyle_tt',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='ketquachuyenkhoa',
            name='chi_so',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ketquatongquat',
            name='ket_qua_dieu_tri',
            field=models.CharField(blank=True, choices=[('1', 'Khỏi'), ('2', 'Đỡ'), ('3', 'Không Thay Đổi'), ('4', 'Nặng Hơn'), ('5', 'Tử Vong')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='lichhenkham',
            name='ly_do_vvien',
            field=models.CharField(blank=True, choices=[('1', 'Đúng Tuyến'), ('2', 'Cấp Cứu'), ('3', 'Trái Tuyến'), ('4', 'Thông Tuyến')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='phongkham',
            name='ma_cskcb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dichvukham',
            name='khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.danhmuckhoa'),
        ),
    ]
