# Generated by Django 3.1.5 on 2021-01-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20210122_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucChuongBenh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.CharField(blank=True, max_length=5, null=True)),
                ('ma_chuong', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_chuong', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Danh Mục Chương Bệnh',
                'verbose_name_plural': 'Danh Mục Chương Bệnh',
            },
        ),
        migrations.AlterModelOptions(
            name='danhmucbenh',
            options={'verbose_name': 'Danh Mục Bệnh', 'verbose_name_plural': 'Danh Mục Bệnh'},
        ),
        migrations.AlterModelOptions(
            name='danhmuckhoa',
            options={'verbose_name': 'Danh Mục Khoa', 'verbose_name_plural': 'Danh Mục Khoa'},
        ),
        migrations.AlterModelOptions(
            name='duongdungthuoc',
            options={'verbose_name': 'Đường Dùng Thuốc', 'verbose_name_plural': 'Đường Dùng Thuốc'},
        ),
        migrations.AlterModelOptions(
            name='goithau',
            options={'verbose_name': 'Gói Thầu', 'verbose_name_plural': 'Gói Thầu'},
        ),
        migrations.AlterModelOptions(
            name='nhomchiphi',
            options={'verbose_name': 'Nhóm Chi Phí', 'verbose_name_plural': 'Nhóm Chi Phí'},
        ),
        migrations.AlterModelOptions(
            name='nhomtainan',
            options={'verbose_name': 'Nhóm Tai Nạn', 'verbose_name_plural': 'Nhóm Tai Nạn'},
        ),
        migrations.AlterModelOptions(
            name='thietbi',
            options={'verbose_name': 'Thiết Bị', 'verbose_name_plural': 'Thiết Bị'},
        ),
        migrations.AddField(
            model_name='danhmucbenh',
            name='ma_nhom_bcao_byt',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='danhmucbenh',
            name='ma_nhom_chi_tiet',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DanhMucNhomBenh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom_chinh', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_nhom_chinh', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_nhom_phu_1', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_nhom_phu_1', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_nhom_phu_2', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_nhom_phu_2', models.CharField(blank=True, max_length=255, null=True)),
                ('chuong_benh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhom_benh', to='clinic.danhmucchuongbenh')),
            ],
            options={
                'verbose_name': 'Danh Mục Nhóm Bệnh',
                'verbose_name_plural': 'Danh Mục Nhóm Bệnh',
            },
        ),
        migrations.CreateModel(
            name='DanhMucLoaiBenh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_loai', models.CharField(blank=True, max_length=10, null=True)),
                ('ten_loai', models.CharField(blank=True, max_length=255, null=True)),
                ('nhom_benh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loai_benh', to='clinic.danhmucnhombenh')),
            ],
            options={
                'verbose_name': 'Danh Mục Loại Bệnh',
                'verbose_name_plural': 'Danh Mục Loại Bệnh',
            },
        ),
        migrations.AddField(
            model_name='danhmucbenh',
            name='loai_benh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benh', to='clinic.danhmucloaibenh'),
        ),
    ]
