# Generated by Django 3.1.5 on 2021-01-23 04:59

import clinic.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20210122_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePhongKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=clinic.models.file_url)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tài Liệu Phòng Khám',
                'verbose_name_plural': 'Tài Liệu Phòng Khám',
            },
        ),
    ]
