# Generated by Django 3.1.5 on 2021-01-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_dichvukham_nhom_chi_phi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketquatongquat',
            name='ma_benh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.danhmucbenh'),
        ),
    ]
