# Generated by Django 3.1.5 on 2021-01-25 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_ketquatongquat_ma_benh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chisoxetnghiem',
            name='dich_vu_kham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chi_so_xet_nghiem', to='clinic.dichvukham'),
        ),
    ]
