# Generated by Django 3.1.5 on 2021-01-29 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20210127_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mauphieu',
            options={'verbose_name': 'Mẫu Phiếu', 'verbose_name_plural': 'Mẫu Phiếu'},
        ),
        migrations.AddField(
            model_name='lichhenkham',
            name='ma_lich_hen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lichhenkham',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benh_nhan_hen_kham', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lichhenkham',
            name='nguoi_phu_trach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_phu_trach', to=settings.AUTH_USER_MODEL),
        ),
    ]
