# Generated by Django 3.1.5 on 2021-01-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_auto_20210129_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichhenkham',
            name='ma_lich_hen',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
