# Generated by Django 3.1.5 on 2021-01-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_auto_20210129_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketquaxetnghiem',
            name='ket_qua_chuyen_khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua_xet_nghiem', to='clinic.ketquachuyenkhoa'),
        ),
    ]
