# Generated by Django 3.1.5 on 2021-02-01 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20210201_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketquachuyenkhoa',
            name='phan_khoa_kham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua_chuyen_khoa', to='clinic.phankhoakham'),
        ),
    ]
