# Generated by Django 3.1.5 on 2021-02-04 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_auto_20210201_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketquachuyenkhoa',
            name='html',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HtmlKetQua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('ket_qua_chuyen_khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='html_ket_qua', to='clinic.ketquachuyenkhoa')),
                ('phan_khoa_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.phankhoakham')),
            ],
            options={
                'verbose_name': 'Kết Quả Dạng HTML',
                'verbose_name_plural': 'Kết Quả Dạng HTML',
            },
        ),
    ]
