# Generated by Django 3.1.5 on 2021-02-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_auto_20210204_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichvukham',
            name='html',
            field=models.BooleanField(default=False),
        ),
    ]
