# Generated by Django 3.1.6 on 2021-02-17 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_dichvukham_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuoikham',
            name='bac_si_dam_nhan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bac_si_chuoi_kham', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chuoikham',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuoi_kham', to=settings.AUTH_USER_MODEL),
        ),
    ]
