# Generated by Django 3.1.6 on 2021-02-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_auto_20210217_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinhThanh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
