# Generated by Django 3.1.6 on 2021-02-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0023_tinhthanh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TinhThanh',
        ),
    ]
