# Generated by Django 3.1.6 on 2021-02-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0024_delete_tinhthanh'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinhThanh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tinh', models.CharField(max_length=10, unique=True)),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_diem', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuanHuyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_huyen', models.CharField(max_length=10, unique=True)),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_diem', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('tinh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quan_huyen', to='clinic.tinhthanh')),
            ],
        ),
        migrations.CreateModel(
            name='PhuongXa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_xa', models.CharField(max_length=10, unique=True)),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_diem', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('huyen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phuong_xa', to='clinic.quanhuyen')),
            ],
        ),
    ]
