# Generated by Django 3.1.6 on 2021-02-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_auto_20210221_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='district_id',
            new_name='district',
        ),
    ]
