# Generated by Django 3.1.6 on 2021-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0028_auto_20210221_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lien_tuc_5_nam_tu',
            field=models.DateField(blank=True, null=True),
        ),
    ]
