# Generated by Django 3.1.6 on 2021-03-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_user_lien_tuc_5_nam_tu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baidang',
            name='tieu_de',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
