# Generated by Django 3.1.7 on 2021-03-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0033_auto_20210323_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baidang',
            options={'permissions': (('can_add_news', 'Thêm bài đăng'), ('can_change_news', 'Thay đổi bài đăng'), ('can_view_news', 'Xem bài đăng'), ('can_delete_news', 'Xóa bài đăng')), 'verbose_name': 'Bài Đăng', 'verbose_name_plural': 'Bài Đăng'},
        ),
        migrations.AlterModelOptions(
            name='chisoxetnghiem',
            options={'permissions': (('can_add_test_values', 'Thêm chỉ số xét nghiệm'), ('can_change_test_values', 'Thay đổi chỉ số xét nghiệm'), ('can_view_test_values', 'Xem chỉ số xét nghiệm'), ('can_delete_test_values', 'Xóa chỉ số xét nghiệm')), 'verbose_name': 'Chỉ Số Xét Nghiệm', 'verbose_name_plural': 'Chỉ Số Xét Nghiệm'},
        ),
        migrations.AlterModelOptions(
            name='chuoikham',
            options={'permissions': (('can_add_assignment_chain', 'Thêm chuỗi khám'), ('can_change_assignment_chain', 'Thay đổi chuỗi khám'), ('can_view_assignment_chain', 'Xem chuỗi khám'), ('can_view_assignment_chain_result', 'Xem kết quả chuỗi khám'), ('can_delete_assignment_chain', 'Xóa chuỗi khám'), ('can_delete_assignment_chain_result', 'Xóa kết quả chuỗi khám')), 'verbose_name': 'Chuỗi Khám', 'verbose_name_plural': 'Chuỗi Khám'},
        ),
        migrations.AlterModelOptions(
            name='dichvukham',
            options={'permissions': (('can_add_service', 'Thêm dịch vụ kỹ thuật'), ('can_change_service', 'Thay đổi dịch vụ kỹ thuật'), ('can_view_service', 'Xem dịch vụ kỹ thuật'), ('can_delete_service', 'Xóa dịch vụ kỹ thuật'), ('can_view_service_price', 'Xem giá dịch vụ kỹ thuật')), 'verbose_name': 'Dịch Vụ Khám', 'verbose_name_plural': 'Dịch Vụ Khám'},
        ),
        migrations.AlterModelOptions(
            name='ketquachuyenkhoa',
            options={'permissions': (('can_add_specialty_result', 'Thêm kết quả chuyên khoa'), ('can_view_specialty_result', 'Xem kết quả chuyên khoa'), ('can_change_specialty_result', 'Thay đổi kết quả chuyên khoa'), ('can_delete_specialty_result', 'Xóa kết quả chuyên khoa')), 'verbose_name': 'Kết Quả Chuyên Khoa', 'verbose_name_plural': 'Kết Quả Chuyên Khoa'},
        ),
        migrations.AlterModelOptions(
            name='ketquatongquat',
            options={'permissions': (('can_add_general_result', 'Thêm kết quả tổng quát'), ('can_view_general_result', 'Xem kết quả tổng quát'), ('can_change_general_result', 'Thay đổi kết quả tổng quát'), ('can_delete_general_result', 'Xóa kết quả tổng quát')), 'verbose_name': 'Kết Quả Tổng Quát', 'verbose_name_plural': 'Kết Quả Tổng Quát'},
        ),
        migrations.AlterModelOptions(
            name='ketquaxetnghiem',
            options={'permissions': (('can_add_lab_result', 'Thêm kết quả xét nghiệm'), ('can_change_lab_result', 'Thay đổi kết quả xét nghiệm'), ('can_view_lab_result', 'Xem kết quả xét nghiệm'), ('can_delete_lab_result', 'Xóa kết quả xét nghiệm')), 'verbose_name': 'Kết Quả Xét Nghiệm', 'verbose_name_plural': 'Kết Quả Xét Nghiệm'},
        ),
        migrations.AlterModelOptions(
            name='lichhenkham',
            options={'permissions': (('can_add_appointment', 'Thêm lịch hẹn'), ('can_change_appointment', 'Thay đổi lịch hẹn'), ('can_view_appointment', 'Xem lịch hẹn'), ('can_delete_appointment', 'Xóa lịch hẹn'), ('can_make_reexamination', 'Thêm lịch hẹn tái khám')), 'verbose_name': 'Lịch Hẹn Khám', 'verbose_name_plural': 'Lịch Hẹn Khám'},
        ),
        migrations.AlterModelOptions(
            name='mauphieu',
            options={'permissions': (('can_add_analysis_note', 'Thêm mẫu phiếu'), ('can_change_analysis_note', 'Thay đổi mẫu phiếu'), ('can_view_analysis_note', 'Xem mấu phiếu'), ('can_delete_analysis_note', 'Xóa mẫu phiếu')), 'verbose_name': 'Mẫu Phiếu', 'verbose_name_plural': 'Mẫu Phiếu'},
        ),
        migrations.AlterModelOptions(
            name='phankhoakham',
            options={'permissions': (('can_add_service_assignment', 'Thêm phân khoa khám'), ('can_view_service_assignment', 'Xem phân khoa khám'), ('can_delete_service_assignment', 'Xóa phân khoa khám')), 'verbose_name': 'Phân Khoa Khám', 'verbose_name_plural': 'Phân Khoa Khám'},
        ),
        migrations.AlterModelOptions(
            name='phongchucnang',
            options={'permissions': (('can_add_consulting_room', 'Thêm phòng chức năng'), ('can_change_consulting_room', 'Chỉnh sửa phòng chức năng'), ('can_view_consulting_room', 'Xem phòng chức năng'), ('can_delete_consulting_room', 'Xóa phòng chức năng')), 'verbose_name': 'Phòng Chức Năng', 'verbose_name_plural': 'Phòng Chức Năng'},
        ),
        migrations.AlterModelOptions(
            name='phongkham',
            options={'permissions': (('can_add_clinic_info', 'Thêm thông tin phòng khám'), ('can_change_clinic_info', 'Thay đổi thông tin phòng khám')), 'verbose_name': 'Phòng Khám', 'verbose_name_plural': 'Phòng Khám'},
        ),
    ]
