# Generated by Django 3.1.7 on 2021-03-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0040_auto_20210326_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lichhenkham',
            options={'permissions': (('can_add_appointment', 'Thêm lịch hẹn'), ('can_change_appointment', 'Thay đổi lịch hẹn'), ('can_view_appointment', 'Xem lịch hẹn'), ('can_delete_appointment', 'Xóa lịch hẹn'), ('can_make_reexamination', 'Thêm lịch hẹn tái khám'), ('can_confirm_appoinment', 'Xác nhận lịch hẹn'), ('can_confirm_do_examination', 'Xác nhận khám')), 'verbose_name': 'Lịch Hẹn Khám', 'verbose_name_plural': 'Lịch Hẹn Khám'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_user', 'Thêm người dùng'), ('can_add_staff_user', 'Thêm nhân viên'), ('can_change_user_info', 'Chỉnh sửa người dùng'), ('can_change_staff_user_info', 'Chỉnh sửa nhân viên'), ('can_change_password_user', 'Thay đổi mật khẩu người dùng'), ('can_change_password_staff_user', 'Thay đổi mật khẩu nhân viên'), ('can_view_user_info', 'Xem người dùng'), ('can_view_staff_user_info', 'Xem nhân viên'), ('can_delete_user', 'Xóa người dùng'), ('can_delete_staff_user', 'Xóa nhân viên'), ('general_view', 'Xem Tổng Quan Trang Chủ'), ('reception_department_module_view', 'Phòng Ban Lễ Tân'), ('finance_department_module_view', 'Phòng Ban Tài Chính'), ('specialist_department_module_view', 'Phòng Ban Chuyên Gia'), ('preclinical_department_module_view', 'Phòng Ban Lâm Sàng'), ('medicine_department_module_view', 'Phòng Ban Thuốc'), ('general_revenue_view', 'Xem Doanh Thu Phòng Khám'), ('view_checkout_list', 'Xem Danh Sách Thanh Toán Tài Chính'), ('export_insurance_data', 'Xuất Bảo Hiểm Tài Chính'), ('can_export_list_of_patient_insurance_coverage', 'Xuất Danh Sách Bệnh Nhân Bảo Hiểm Chi Trả'))},
        ),
    ]
