# Generated by Django 3.1.7 on 2021-03-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0043_auto_20210326_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ketquachuyenkhoa',
            options={'permissions': (('can_add_specialty_result', 'Thêm kết quả chuyên khoa'), ('can_view_specialty_result', 'Xem kết quả chuyên khoa'), ('can_change_specialty_result', 'Thay đổi kết quả chuyên khoa'), ('can_delete_specialty_result', 'Xóa kết quả chuyên khoa'), ('can_view_history_specialty_result', 'Xem lịch sử khám chuyên khoa')), 'verbose_name': 'Kết Quả Chuyên Khoa', 'verbose_name_plural': 'Kết Quả Chuyên Khoa'},
        ),
        migrations.AlterModelOptions(
            name='phankhoakham',
            options={'permissions': (('can_add_service_assignment', 'Thêm phân khoa khám'), ('can_view_service_assignment', 'Xem phân khoa khám'), ('can_delete_service_assignment', 'Xóa phân khoa khám'), ('can_stop_serivce_assignment', 'Dừng khám')), 'verbose_name': 'Phân Khoa Khám', 'verbose_name_plural': 'Phân Khoa Khám'},
        ),
    ]
