# Generated by Django 3.1.7 on 2021-03-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0044_auto_20210326_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phankhoakham',
            options={'permissions': (('can_add_service_assignment', 'Thêm phân khoa khám'), ('can_view_service_assignment', 'Xem phân khoa khám'), ('can_delete_service_assignment', 'Xóa phân khoa khám'), ('can_do_specialist_examination', 'Có thể khám chuyên khoa'), ('can_stop_serivce_assignment', 'Dừng khám')), 'verbose_name': 'Phân Khoa Khám', 'verbose_name_plural': 'Phân Khoa Khám'},
        ),
    ]
