# Generated by Django 3.2 on 2021-04-23 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0047_auto_20210327_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mauphieu',
            options={'permissions': (('can_add_analysis_note', 'Thêm mẫu phiếu'), ('can_change_analysis_note', 'Thay đổi mẫu phiếu'), ('can_view_analysis_note', 'Xem mẫu phiếu'), ('can_delete_analysis_note', 'Xóa mẫu phiếu')), 'verbose_name': 'Mẫu Phiếu', 'verbose_name_plural': 'Mẫu Phiếu'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_user', 'Thêm người dùng'), ('can_add_staff_user', 'Thêm nhân viên'), ('can_change_user_info', 'Chỉnh sửa người dùng'), ('can_change_staff_user_info', 'Chỉnh sửa nhân viên'), ('can_change_password_user', 'Thay đổi mật khẩu người dùng'), ('can_change_password_staff_user', 'Thay đổi mật khẩu nhân viên'), ('can_view_user_info', 'Xem người dùng'), ('can_view_staff_user_info', 'Xem nhân viên'), ('can_delete_user', 'Xóa người dùng'), ('can_delete_staff_user', 'Xóa nhân viên'), ('general_view', 'Xem Tổng Quan Trang Chủ'), ('reception_department_module_view', 'Phòng Ban Lễ Tân'), ('finance_department_module_view', 'Phòng Ban Tài Chính'), ('specialist_department_module_view', 'Phòng Ban Chuyên Gia'), ('preclinical_department_module_view', 'Phòng Ban Lâm Sàng'), ('medicine_department_module_view', 'Phòng Ban Thuốc'), ('general_revenue_view', 'Xem Doanh Thu Phòng Khám'), ('can_view_checkout_list', 'Xem Danh Sách Thanh Toán Tài Chính'), ('export_insurance_data', 'Xuất Bảo Hiểm Tài Chính'), ('can_export_list_of_patient_insurance_coverage', 'Xuất Danh Sách Bệnh Nhân Bảo Hiểm Chi Trả'), ('can_view_list_of_patient', 'Xem Danh Sách Bệnh Nhân Chờ'), ('can_bao_cao_thuoc', 'Báo Cáo Thuốc'))},
        ),
        migrations.AddField(
            model_name='htmlketqua',
            name='ket_qua_tong_quat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='html_ket_qua_tong_quat', to='clinic.ketquatongquat'),
        ),
        migrations.AddField(
            model_name='ketquachuyenkhoa',
            name='bac_si_chuyen_khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ket_qua_bac_si_chuyen_khoa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ketquachuyenkhoa',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ketquatongquat',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mauphieu',
            name='codename',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phongchucnang',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bacsi',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bac_si', to=settings.AUTH_USER_MODEL),
        ),
    ]
