# Generated by Django 3.2 on 2021-05-11 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0050_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhomChiSoXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nhóm Chỉ Số Xét Nghiệm',
                'verbose_name_plural': 'Nhóm Chỉ Số Xét Nghiệm',
            },
        ),
        migrations.AddField(
            model_name='lichhenkham',
            name='thanh_toan_sau',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chuoikham',
            name='lich_hen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_chuoi_kham', to='clinic.lichhenkham'),
        ),
        migrations.AlterField(
            model_name='lichhenkham',
            name='loai_dich_vu',
            field=models.CharField(blank=True, choices=[('kham_chua_benh', 'Khám Chữa Bệnh'), ('kham_suc_khoe', 'Khám Sức Khỏe'), ('kham_theo_yeu_cau', 'Khám Theo Yêu Cầu')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='chisoxetnghiem',
            name='nhom_chi_so',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.nhomchisoxetnghiem'),
        ),
    ]
