# Generated by Django 3.2.4 on 2021-07-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0052_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhongLamSang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_lam_sang', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Phòng Lâm Sàng',
            },
        ),
        migrations.CreateModel(
            name='NhomDichVuKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom_dich_vu', models.CharField(blank=True, max_length=255, null=True)),
                ('dich_vu_kham', models.ManyToManyField(blank=True, null=True, to='clinic.DichVuKham')),
            ],
            options={
                'verbose_name_plural': 'Nhóm Dịch Vụ Khám',
            },
        ),
        migrations.AddField(
            model_name='lichhenkham',
            name='phong_lam_sang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_hen_theo_phong', to='clinic.phonglamsang'),
        ),
    ]
