# Generated by Django 3.2.4 on 2021-07-14 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0053_auto_20210712_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhenkham',
            name='nhom_dich_vu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.nhomdichvukham'),
        ),
    ]
