# Generated by Django 3.1.5 on 2021-01-19 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medicine.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongTy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_cong_ty', models.CharField(max_length=255, verbose_name='Tên Công Ty')),
                ('giay_phep_kinh_doanh', models.CharField(blank=True, max_length=255, null=True, verbose_name='Giấy phép kinh doanh')),
                ('dia_chi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('so_lien_lac', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số liên lạc')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email công ty')),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả công ty')),
                ('loai_cung', models.CharField(blank=True, choices=[('thuoc', 'Thuốc'), ('vat_tu', 'Vật Tư')], max_length=255, null=True)),
                ('ngay_gio_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giờ tạo')),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Công Ty',
                'verbose_name_plural': 'Công Ty',
            },
        ),
        migrations.CreateModel(
            name='DonThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don_thuoc', models.CharField(max_length=50, unique=True)),
                ('ly_do_chinh_sua', models.TextField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('bac_si_ke_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bac_si_ke_don', to=settings.AUTH_USER_MODEL)),
                ('benh_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_thuoc', to=settings.AUTH_USER_MODEL)),
                ('chuoi_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_thuoc_chuoi_kham', to='clinic.chuoikham')),
            ],
            options={
                'verbose_name': 'Đơn Thuốc',
                'verbose_name_plural': 'Đơn Thuốc',
            },
        ),
        migrations.CreateModel(
            name='NhomThau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom_thau', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhomVatTu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom_vtyt', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_nhom_vtyt', models.CharField(blank=True, max_length=255, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Nhóm Vật Tư',
                'verbose_name_plural': 'Nhóm Vật Tư',
            },
        ),
        migrations.CreateModel(
            name='Thuoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ma_thuoc', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ma_hoat_chat', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mã hoạt chất')),
                ('ten_hoat_chat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên hoạt chất')),
                ('duong_dung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dùng')),
                ('ham_luong', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hàm lượng')),
                ('ten_thuoc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên thuốc')),
                ('so_dang_ky', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số đăng ký')),
                ('dong_goi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đóng gói')),
                ('don_vi_tinh', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đơn vị tính')),
                ('don_gia', models.CharField(max_length=50, null=True, verbose_name='Đơn giá')),
                ('don_gia_tt', models.CharField(max_length=50, null=True, verbose_name='Đơn giá thành tiền')),
                ('so_lo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số Lô')),
                ('so_luong_kha_dung', models.IntegerField(blank=True, null=True, verbose_name='Số lượng khả dụng')),
                ('ma_cskcb', models.CharField(blank=True, max_length=50, null=True)),
                ('hang_sx', models.CharField(blank=True, max_length=255, null=True)),
                ('nuoc_sx', models.CharField(blank=True, max_length=50, null=True)),
                ('quyet_dinh', models.CharField(blank=True, max_length=10, null=True)),
                ('loai_thuoc', models.CharField(blank=True, choices=[('1', 'Tân Dược'), ('2', 'Chế phẩm YHCT'), ('3', 'Vị thuốc YHCT'), ('4', 'Phóng xạ'), ('5', 'Thực phẩm bảo vệ sức khỏe')], max_length=255, null=True)),
                ('cong_bo', models.CharField(blank=True, max_length=50, null=True)),
                ('loai_thau', models.CharField(blank=True, choices=[('1', 'Thầu tập trung'), ('2', 'Thầu riêng tại BV')], max_length=255, null=True)),
                ('bao_hiem', models.BooleanField(blank=True, default=False, null=True)),
                ('han_su_dung', models.DateField(blank=True, null=True)),
                ('ngay_san_xuat', models.DateField(blank=True, null=True)),
                ('ngay_gio_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giờ tạo')),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True)),
                ('diem_tich', models.PositiveIntegerField(blank=True, null=True)),
                ('cong_ty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thuoc_cong_ty', to='medicine.congty')),
                ('nhom_thau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.nhomthau')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Thuốc',
            },
        ),
        migrations.CreateModel(
            name='TrangThaiDonThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Trạng Thái Đơn Thuốc',
                'verbose_name_plural': 'Trạng Thái Đơn Thuốc',
            },
        ),
        migrations.CreateModel(
            name='VatTu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.CharField(blank=True, max_length=50, null=True)),
                ('ma_hieu', models.CharField(blank=True, max_length=30, null=True)),
                ('ma_vtyt_bv', models.CharField(blank=True, max_length=100, null=True)),
                ('ten_vtyt_bv', models.CharField(blank=True, max_length=250, null=True)),
                ('quy_cach', models.CharField(blank=True, max_length=100, null=True)),
                ('hang_sx', models.CharField(blank=True, max_length=100, null=True)),
                ('nuoc_sx', models.CharField(blank=True, max_length=100, null=True)),
                ('don_vi_tinh', models.CharField(blank=True, max_length=20, null=True)),
                ('bao_hiem', models.BooleanField(default=False)),
                ('don_gia', models.CharField(max_length=50, null=True, verbose_name='Đơn giá')),
                ('don_gia_tt', models.CharField(max_length=50, null=True, verbose_name='Đơn giá thành tiền')),
                ('quyet_dinh', models.CharField(blank=True, max_length=20, null=True)),
                ('cong_bo', models.CharField(blank=True, max_length=10, null=True)),
                ('dinh_muc', models.CharField(blank=True, max_length=10, null=True)),
                ('so_luong_kha_dung', models.IntegerField(verbose_name='Số lượng khả dụng')),
                ('loai_thau', models.CharField(blank=True, choices=[('1', 'Thầu tập trung'), ('2', 'Thầu riêng tại BV')], max_length=255, null=True)),
                ('ngay_gio_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giờ tạo')),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nha_thau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vat_tu_cong_ty', to='medicine.congty')),
                ('nhom_vat_tu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhom_vat_tu', to='medicine.nhomvattu')),
            ],
            options={
                'verbose_name': 'Vật Tư',
                'verbose_name_plural': 'Vật Tư',
            },
        ),
        migrations.CreateModel(
            name='ThuocLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateTimeField(verbose_name='Ngày giờ')),
                ('quy_trinh', models.CharField(choices=[('I', 'In'), ('O', 'Out')], max_length=1, verbose_name='Quy trình')),
                ('so_luong', models.IntegerField(default=0, verbose_name='Số lượng')),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuoc_logs', to='medicine.thuoc', verbose_name='Thuốc')),
            ],
            options={
                'verbose_name': 'Thuốc Log',
                'verbose_name_plural': 'Thuốc Log',
            },
        ),
        migrations.CreateModel(
            name='LichSuTrangThaiDonThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.TextField()),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('don_thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.donthuoc')),
                ('trang_thai_don_thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.trangthaidonthuoc')),
            ],
        ),
        migrations.CreateModel(
            name='KeVatTu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(blank=True, null=True)),
                ('bao_hiem', models.BooleanField(default=False)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('hoa_don_vat_tu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ke_don', to='finance.hoadonvattu')),
                ('vat_tu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.vattu')),
            ],
            options={
                'verbose_name': 'Kê Vật Tư ',
                'verbose_name_plural': 'Kê Vật Tư',
            },
        ),
        migrations.CreateModel(
            name='KeDonThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cach_dung', models.TextField()),
                ('so_luong', models.PositiveIntegerField()),
                ('ghi_chu', models.TextField()),
                ('bao_hiem', models.BooleanField(default=False)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('don_thuoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ke_don', to='medicine.donthuoc')),
                ('thuoc', models.ForeignKey(on_delete=models.SET(medicine.models.get_sentinel_thuoc), to='medicine.thuoc')),
            ],
            options={
                'verbose_name': 'Kê Đơn Thuốc',
                'verbose_name_plural': 'Kê Đơn Thuốc',
            },
        ),
        migrations.CreateModel(
            name='GiaThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.DecimalField(decimal_places=3, max_digits=10)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(blank=True, null=True)),
                ('id_thuoc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gia_thuoc', to='medicine.thuoc')),
            ],
        ),
        migrations.AddField(
            model_name='donthuoc',
            name='trang_thai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.trangthaidonthuoc'),
        ),
        migrations.CreateModel(
            name='ChiTietThuoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_muoi', models.CharField(max_length=255, verbose_name='Tên thuốc con')),
                ('ham_luong', models.CharField(max_length=255, verbose_name='Hàm lượng')),
                ('mo_ta', models.CharField(max_length=255, verbose_name='Mô tả')),
                ('ngay_gio_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giờ tạo')),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True)),
                ('id_thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.thuoc', verbose_name='Thuốc')),
            ],
            options={
                'verbose_name': 'Chi Tiết Thuốc',
                'verbose_name_plural': 'Chi Tiết Thuốc',
            },
        ),
        migrations.CreateModel(
            name='BaoHiemThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muc_bao_hiem', models.PositiveIntegerField()),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(blank=True, null=True)),
                ('id_thuoc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bao_hiem_thuoc', to='medicine.thuoc')),
            ],
        ),
    ]
