# Generated by Django 3.1.5 on 2021-01-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20210122_1441'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoc',
            name='muc_huong',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='thuoc',
            name='nhom_chi_phi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.nhomchiphi'),
        ),
        migrations.AddField(
            model_name='thuoc',
            name='pham_vi',
            field=models.CharField(blank=True, choices=[('1', 'Thuốc trong phạm vi hưởng BHYT'), ('2', 'Thuốc ngoài phạm vi hưởng BHTY')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='thuoc',
            name='tyle_tt',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vattu',
            name='goi_vtyt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.goithau'),
        ),
        migrations.AddField(
            model_name='vattu',
            name='muc_huong',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vattu',
            name='pham_vi',
            field=models.CharField(blank=True, choices=[('1', 'Vật tư trong phạm vi hưởng BHYT'), ('2', 'Vật tư ngoài phạm vi hưởng BHTY')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vattu',
            name='tyle_tt',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='duong_dung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.duongdungthuoc'),
        ),
    ]
