# Generated by Django 3.1.5 on 2021-01-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20210124_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kedonthuoc',
            name='don_thuoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ke_don', to='medicine.donthuoc'),
        ),
    ]
