# Generated by Django 3.1.5 on 2021-02-02 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20210124_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kedonthuoc',
            name='thuoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.thuoc'),
        ),
    ]
