# Generated by Django 3.1.6 on 2021-03-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20210202_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kedonthuoc',
            name='thoi_gian_cap_nhat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='kedonthuoc',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
