# Generated by Django 3.1.7 on 2021-03-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20210310_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donthuoc',
            options={'permissions': (('can_add_prescription', 'Thêm đơn thuốc'), ('can_change_prescription', 'Thay đổi đơn thuốc'), ('can_view_prescription', 'Xem đơn thuốc'), ('can_delete_prescription', 'Xóa đơn thuốc'), ('can_print_prescription', 'In đơn thuốc')), 'verbose_name': 'Đơn Thuốc', 'verbose_name_plural': 'Đơn Thuốc'},
        ),
        migrations.AlterModelOptions(
            name='kedonthuoc',
            options={'permissions': (('can_prescribe', 'Kê đơn'),), 'verbose_name': 'Kê Đơn Thuốc', 'verbose_name_plural': 'Kê Đơn Thuốc'},
        ),
        migrations.AlterModelOptions(
            name='kevattu',
            options={'permissions': (('can_list_medical_supplies', 'Kê vật tư'),), 'verbose_name': 'Kê Vật Tư ', 'verbose_name_plural': 'Kê Vật Tư'},
        ),
        migrations.AlterModelOptions(
            name='thuoc',
            options={'permissions': (('can_add_medicine', 'Thêm thuốc'), ('can_change_medicine', 'Thay đổi thuốc'), ('can_view_medicine', 'Xem thuốc'), ('can_delete_medicine', 'Xóa thuốc'), ('can_view_import_medicine_price', 'Xem giá thuốc nhập'), ('can_view_export_medicine_price', 'Xem giá thuốc bán ra'), ('can_export_medicine_list', 'Xuất danh sách thuốc')), 'verbose_name': 'Thuốc', 'verbose_name_plural': 'Thuốc'},
        ),
        migrations.AlterModelOptions(
            name='vattu',
            options={'permissions': (('can_add_medical_supplies', 'Thêm vật tư y tế'), ('can_change_medical_supplies', 'Thay đổi vật tư y tế'), ('can_view_medical_supplies', 'Xem vật tư y tế'), ('can_delete_medical_supplies', 'Xóa vật tư y tế'), ('can_export_medical_supplies_list', 'Xuất danh sách vật tư y tế')), 'verbose_name': 'Vật Tư', 'verbose_name_plural': 'Vật Tư'},
        ),
    ]
