# Generated by Django 3.1.7 on 2021-03-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_auto_20210324_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congty',
            options={'permissions': (('can_add_company', 'Thêm nguồn cung'), ('can_change_company', 'Thay đổi nguồn cung'), ('can_view_company', 'Xem nguồn cung'), ('can_delete_company', 'Xóa nguồn cung')), 'verbose_name': 'Công Ty', 'verbose_name_plural': 'Công Ty'},
        ),
    ]
