# Generated by Django 3.1.7 on 2021-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_auto_20210326_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoc',
            name='stt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
