# Generated by Django 3.2 on 2021-04-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0012_auto_20210423_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thuoc',
            name='stt',
        ),
    ]
