# Generated by Django 3.2 on 2021-04-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_remove_thuoc_stt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thuoc',
            name='nhom_thuoc',
        ),
    ]
