# Generated by Django 3.1.7 on 2021-04-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_thuoc_gia_bhyt'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoclog',
            name='bao_hiem',
            field=models.BooleanField(default=True),
        ),
    ]
