# Generated by Django 3.2 on 2021-04-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_remove_thuoc_nhom_thuoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thuoc',
            name='gia_bhyt',
        ),
    ]
