# Generated by Django 3.2 on 2021-04-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0015_remove_thuoc_gia_bhyt'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoc',
            name='gia_bhyt',
            field=models.IntegerField(max_length=50, null=True, verbose_name='Giá bảo hiểm y tế'),
        ),
        migrations.AddField(
            model_name='thuoc',
            name='nhom_thuoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhom_thuoc', to='medicine.nhomthuoc'),
        ),
    ]
