# Generated by Django 3.2 on 2021-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0016_auto_20210423_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoc',
            name='stt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
