# Generated by Django 3.2 on 2021-05-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0018_auto_20210426_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuoc',
            name='don_gia',
            field=models.IntegerField(null=True, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='don_gia_tt',
            field=models.IntegerField(null=True, verbose_name='Đơn giá thành tiền'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='gia_bhyt',
            field=models.IntegerField(null=True, verbose_name='Giá bảo hiểm y tế'),
        ),
    ]
